name: Download Podcasts to S3

on:
  workflow_dispatch: # Allows manual triggering
  workflow_run:
    workflows: ["Update Weekly Podcast JSON"] # Name of the workflow that generates the JSON
    types:
      - completed
    branches:
      - main # Or your default branch

jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    # Only run if the triggering workflow was successful or if manually dispatched
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    permissions:
      contents: read # Only needs to read the repo contents (JSON files)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # fetch-depth: 0 # Usually not needed unless accessing git history extensively

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Create temp-media directory
        run: mkdir -p ./temp-media

      - name: Run MP3 download to local script
        # This script now only downloads files to ./temp-media/
        run: bun run ./scripts/downloadMp3sToLocal.ts
    
      - name: Enable NTP sync
        run: |
          sudo timedatectl set-ntp true
          sleep 5  # 等待几秒让时间同步生效
          date      # 打印当前时间验证

      - name: Upload temp-media folder to S3
        env: # Pass secrets to the npx command's environment
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_BUCKET_PREFIX: ${{ secrets.S3_PATH_PREFIX || '/' }} # Default to root if not set
        run: |
          npx @web.worker/s3-upload-folder \
            --dist ./temp-media \
            --ak "$S3_ACCESS_KEY_ID" \
            --sk "$S3_SECRET_ACCESS_KEY" \
            --endpoint "$S3_ENDPOINT_URL" \
            --region "$S3_REGION" \
            --bucket "$S3_BUCKET_NAME" \
            --prefix "$S3_BUCKET_PREFIX"

      - name: Remove temp-media folder
        run: rm -rf ./temp-media
